all:
	g++ -o meeting2_problem1 meeting2_problem1.cpp

dump:
	objdump -d meeting2_problem1 > meeting2_problem1.asm

clean:
	rm -f meeting2_problem1.o meeting2_problem1

run: meeting2_problem1
	./meeting2_problem1
